### ISSUE TITLE
Buffer redrawing becomes very slow

### ISSUE THREAD

**Issue by mashaklzo** [prompt-toolkit/python-prompt-toolkit#834]
I'm doing a lot of heavy drawing into a buffer and after a few minutes it slows down. 

Basically I have a couple of buffers and I'm writing a large amount of text to them in a kind of animation every 1/10 second or so. It starts off refreshing rapidly and starts to slow down. Is there anything I can trigger to make this work?

Setup is something like this:

```
window = Window(BufferControl(buffer=my_buffer,focusable=False,include_default_input_processors=False,input_processors=[FormatText()]))

body = HSplit([
    window
])

root_container = HSplit([
    Window(height=1,
           content=FormattedTextControl(get_titlebar_text),
           align=WindowAlign.CENTER),
    Window(height=1, char='-', style='class:line'),
    body,
])

```
Then I have a thread where I update my_buffer.text - whereby, I get the sluggish behaviour after a short while. Is there a better way of doing this?

I thought I'd ask if there is something I've missed in the docs, I've read everything carefully and have set an app.invalidate() but this doesn't help. Same for the min_redraw_interval and max_render_postpone_time settings.

Thanks!

**Comment by jonathanslenders** [comment]
Hi @mashaklzo,

Just to be sure. Did you try this with the latest prompt_toolkit release? This sounds like an issue that was resolved some time ago.
Otherwise, this is certainly a bug.

**Comment by mashaklzo** [comment]
I upgraded from git to version 2.0.8 and the problem persists. Here's a script that shows how I am using the toolkit:

https://gist.github.com/mashaklzo/c899bf63b39d4bf9cb0e43ac4fc5eb02

If you see anything obvious that would be helpful!

**Comment by jonathanslenders** [comment]
Hi @mashaklzo,
I've been running your script with the latest version this morning, and actually after an hour it was still running fine. Can you please check again by installing the latest version and check that it's actually using that?

**Comment by mashaklzo** [comment]
Wow thank you SO much for testing. I found that by uninstalling and re-installing from source I now  have version 2.0.8 running and as you say, it's hugely improved and working as I hoped! This is really wonderful, thank you again.

**Comment by jonathanslenders** [comment]
No problem! Glad it's working now.
